### ISSUE TITLE
Cooldown

### ISSUE THREAD

**Issue by supertakeru** [imDMK/DoubleJump#16]
Can we get a feature where you can add a cooldown to the double jump in the config?

**Comment by imDMK** [comment]
Hi, if I understand correctly, you want to add delay in jumps. This feature already exists. To enable it, change the **jumpDelayEnabled** option in **jumpConfiguration** section to **true** and set the appropriate delay value in **jumpDelay** (e.g. 10s). 
If you have further questions or suggestions feel free to write!
Regards.
