### ISSUE TITLE
Set limit to double jump

### ISSUE THREAD

**Issue by PorkLiquor** [imDMK/DoubleJump#17]
**Description**
First of all, love this plugin, thanks so much for your contribution, tons of fun! One thing I'd really like is the ability to set a limit on the amount of double jumps as right now it is unlimited with no ability to prevent people from perma-flying.

**Additional context**
Would love an easy command to set dbl jump

**Comment by imDMK** [comment]
Thank you for this suggestion.
An update will come out in a few days.
***Pss...*** If you liked the plugin and want to support me, leave a star project.

**Comment by PorkLiquor** [comment]
> Thank you for this suggestion. An update will come out in a few days. _**Pss...**_ If you liked the plugin and want to support me, leave a star project.

done, your plugin is king :)

**Comment by imDMK** [comment]
Your feature is ready.
But it **needs testing** to find bugs. 
If you are willing to test this feature let me know.

**Comment by PorkLiquor** [comment]
> 

absolutely willing to test, want to share the file? will load it into my server ASAP

**Comment by imDMK** [comment]
[DoubleJump.zip](https://github.com/imDMK/DoubleJump/files/12448190/DoubleJump.zip)
Here you have compiled a jar file.
**Don't test this publicly - it may be unstable.**

**Comment by imDMK** [comment]
Report all your suggestions and any bugs you encounter.
Thanks for testing!
Regards.

**Comment by PorkLiquor** [comment]
hey brother, installed the plugin and the commands are no longer appearing ingame verified it's installed via /plugins but the text is red

**Comment by imDMK** [comment]
What do you mean by commands are no longer appearing?
And what do you mean by text is red?
Could you attach screenshots?

Please make sure you have permission to use these commands.

**Comment by PorkLiquor** [comment]
I use apex hosting see attached images, apologies new to this! When I used the 'pre-loaded' one in the plugin library it worked but when i tried installing it myself no luck.

![db4](https://github.com/imDMK/DoubleJump/assets/143234436/e1402faf-3982-48d6-9052-bcb398da4224)
![db3](https://github.com/imDMK/DoubleJump/assets/143234436/4a3d7145-6427-40a9-a2ad-f4e344c3faa3)
![db2](https://github.com/imDMK/DoubleJump/assets/143234436/c53ccde1-8fdf-483f-9ffa-a5a553616174)
![db1](https://github.com/imDMK/DoubleJump/assets/143234436/3178b7d4-a079-42a8-ad80-7ec0fbcb9904)

**Comment by imDMK** [comment]
Could you please show the error?

**Comment by PorkLiquor** [comment]
there is no error it is just not appearing in game at all, like i used to be able to type /doublejump for various commands and see nothing now

**Comment by imDMK** [comment]
The error appears when starting the plugin, in other words, when the server is turned on.
When the name of the plugin is in red color, it means that it was not loaded correctly and must have thrown an error when trying to enable it.

**Comment by PorkLiquor** [comment]
![image](https://github.com/imDMK/DoubleJump/assets/143234436/4f24a774-c14a-4a36-86e7-eae2bbaaa3fe)
aha found the error see above

**Comment by PorkLiquor** [comment]
running paper 1.20

**Comment by imDMK** [comment]
My mistake. Fixed here. 
[DoubleJump.zip](https://github.com/imDMK/DoubleJump/files/12448655/DoubleJump.zip)

**Comment by PorkLiquor** [comment]
working now! gonna mess around a bit and let you know ty <3

**Comment by imDMK** [comment]
Hey, did you manage to detect anything and how do you rate the new feature?

**Comment by PorkLiquor** [comment]
works great and yes rated the new feature! the only thing i noticed is the double jump propels you forward vs a standard double jump which is fine

**Comment by PorkLiquor** [comment]
https://github.com/imDMK/DoubleJump/assets/143234436/efc4372d-5874-4ef2-8375-05f7dcfc8781

see how it sends you forward instead of jumping directly straight up?

**Comment by PorkLiquor** [comment]
thanks again for all your help :)

**Comment by imDMK** [comment]
I think this is already done physics in Minecraft and probably won't do anything about it. 
This feature has nothing to do with it because I didn't make any changes to the jumping physics, but I'll look into that.
Soon update with your feature and configuration improvement.
Thank you for your help!
Regards.

**Comment by PorkLiquor** [comment]
no problem!
