### ISSUE TITLE
Add way to make region list the allowed list (whitelist), or allow __global__ region usage please

### ISSUE THREAD

**Issue by bobhenl** [imDMK/DoubleJump#22]
**Description**
Hello, I've tried to disable double jump in __global__ region, but it doesn't work. So it would be great if you can add way to switch the blacklist (the regions where you cannot double jump) to whitelist, so we can allow only specific regions. Or another solution would be to make __global__ work.
**Additional context**
    disabledRegions:
    - __global__

**Comment by imDMK** [comment]
Hello, 
Thank you for your issue.

Soon I will release an update with this feature.
Best Regards.

**Comment by bobhenl** [comment]
hi, how it looks @imDMK , please?

**Comment by imDMK** [comment]
> hi, how it looks @imDMK , please?

I am currently working on it. It will take me a while to work through all the functions.

**Comment by bobhenl** [comment]
Great, thanks!

**Comment by bobhenl** [comment]
When is the release coming? @imDMK If not soon, do you think that you can provide me the .jar please?

**Comment by imDMK** [comment]
> When is the release coming? @imDMK If not soon, do you think that you can provide me the .jar please?

Today.
