### ISSUE TITLE
API not detected

### ISSUE THREAD

**Issue by Kifo1** [imDMK/DoubleJump#29]
**Describe the bug**
I use the API in a plugin by adding the API jar as a library to my plugin. The problem is that the original DoubleJump plugin does not detect that my plugin contains the API and the DoubleJumpEvent in my plugin is not triggered. The Maven import from the github description doesn't work as well which means I have to add the dependency via an external jar instead of the maven repository.

**How do you trigger it?**
Just running my plugin with a dependency and the original DoubleJump plugin on one server.

**Console log**
No console log since there is no exception.

**Server version**
1.20.4

**Plugin version**
v2.1.2 and latest API version

**Plugin configuration**
Auto generated config file

**Screenshots or Video**
-

**Additional context**
-

**Comment by imDMK** [comment]
Hello,
Thank you for the issue.

The jitpack dependency issue has been resolved. Try using the dependency from jitpack and let me know if the plugin still doesn't catch the API.

Regards.

**Comment by imDMK** [comment]
Please use 2.1.2 api version.

**Comment by Kifo1** [comment]
Maven can't find this dependency for me. Could you send me the <dependency> tag you use to get the API please?

**Comment by imDMK** [comment]
> Maven can't find this dependency for me. Could you send me the <dependency> tag you use to get the API please?

And how it's going?
