### ISSUE TITLE
Regions don't seems working + enabling fly instead of jump?

### ISSUE THREAD

**Issue by bobhenl** [imDMK/DoubleJump#32]
**Describe the bug**
Hi, I tried various settings of BLACKLISTED & WHITELISTED regions, and neither works.
It 1. writes messages like these when I'm in allowed region:
![image](https://github.com/imDMK/DoubleJump/assets/18662086/ffc1b20d-adec-4077-ac42-cc9e028cf7ec)
2. It gives fly (even to players) instead of double jump
**How do you trigger it?**
Try to use worldguard it doesn't even work for me with default settings, I deleted & generated new folder and these 2 still happen.
**Console log**
Any

**Server version**
1.20.1

**Plugin version**
2.1.3

**Plugin configuration**
Try default one, maybe try to add there region to blacklist & whitelist

**Screenshots or Video**
![image](https://github.com/imDMK/DoubleJump/assets/18662086/c7825d37-2ff4-4c8f-a314-2926f5b8462e)

**Comment by imDMK** [comment]
Hello,
Thanks for the issue. 

I will check that soon.

**Comment by bobhenl** [comment]
When I enable doublejump it gives me fly instead of jump (but my it's caused due to the first bug as well?)

**Comment by imDMK** [comment]
> When I enable doublejump it gives me fly instead of jump (but my it's caused due to the first bug as well?)

I'm trying to determine if the bug is related to worldguard. Please check if the bug still occurs if you disable the worldguard plugin. Thanks!

**Comment by bobhenl** [comment]
No, it happens even when I remove worldguard, as you can see, it allows players flying, I don't know why:
![image](https://github.com/imDMK/DoubleJump/assets/18662086/bd09f221-7393-4b28-8205-13f14603ec40)
![image](https://github.com/imDMK/DoubleJump/assets/18662086/ff579697-2097-45d7-9048-00d7faf0527b)
![image](https://github.com/imDMK/DoubleJump/assets/18662086/0df662b1-03cb-4a2f-a614-1b8f50c94127)
There's still message about the region even when I don't have worldguard installed

**Comment by imDMK** [comment]
I think I fixed this bug. Please tr
[doublejump-v2.1.3.zip](https://github.com/imDMK/DoubleJump/files/14693899/doublejump-v2.1.3.zip)
y using this jar file and let me know if everything is correct.

**Comment by bobhenl** [comment]
Almost work, but when using worldguard & going into disabled region with doublejump enabled, you'll get fly

**Comment by imDMK** [comment]
I recoded worldguard checking system. Should work:
[doublejump-worldguard-fixed.zip](https://github.com/imDMK/DoubleJump/files/14706228/doublejump-worldguard-fixed.zip)

**Comment by bobhenl** [comment]
Still seems to give fly when entering that disabled region

**Comment by imDMK** [comment]
Try this:
[dj-fixed.zip](https://github.com/imDMK/DoubleJump/files/14706689/dj-fixed.zip)

**Comment by bobhenl** [comment]
now regions don't work neither (I can use it in the blacklisted one)

**Comment by imDMK** [comment]
That's weird. Please try this
[dj-fixed-v2.zip](https://github.com/imDMK/DoubleJump/files/14706966/dj-fixed-v2.zip)

If bug still exists, please check the letter case region in wg plugin and configuration.

**Comment by bobhenl** [comment]
still gives fly inside region (but cannot be enabled there)

**Comment by imDMK** [comment]
The bugs have been fixed. I tested several times on localhost with the WorldGuard plugin. Everything works fine for me now, but if it still happens to you, let me know!
[final-fix.zip](https://github.com/imDMK/DoubleJump/files/14725157/final-fix.zip)

**Comment by bobhenl** [comment]
Good job, seems working!
