### ISSUE TITLE
Doublejump enables only on join

### ISSUE THREAD

**Issue by ToXer04** [imDMK/DoubleJump#37]
Doublejump works perfectly, I made it so that players can double jump only in the world "hub" and when they join, since they are in the world hub, they can do it. Whenever they change world it doesn't work anymore, which is great, but when they come back to the hub world they still don't have it.

Logs: https://pastebin.com/QK5vQCvY

Server version: paper-496 (1.20.4)

Plugin version: 2.1.4

Plugin configuration: https://pastebin.com/5Cm2km3M

**Comment by imDMK** [comment]
Hello, thanks for reporting the bug. I understand the issue and will try to fix it as soon as possible and let you know. 
Regards

**Comment by ToXer04** [comment]
Thank you for the quick response... I'll be waiting.

**Comment by imDMK** [comment]
Hi again,
The issue should be fixed, please test this jar on your server and let me know if works correctly

Regards,
[doublejum-fix.zip](https://github.com/imDMK/DoubleJump/files/15295168/doublejum-fix.zip)

**Comment by ToXer04** [comment]
Hi, thansk for the quick fix, it works perfectly.
Thanks again and have a nice one!
