### ISSUE TITLE
where wiki or documentation ?

### ISSUE THREAD

**Issue by LKD-PIX** [imDMK/DoubleJump#38]
wiki link from modrinth just links to issues, scam.

**Comment by imDMK** [comment]
Hi, all the most important documentation is in the plugin description and configuration file. Thanks for the issue, I'll change it. However, nothing is a scam. 
Regards.

**Comment by LKD-PIX** [comment]
Much sorry i were kind of annoyed.

It would be cool if you maybe included an example config in the GH wiki setting, as many people, including me, first dive into configurability and documents before installing a plugin.

:)
